language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - nvm install
  - npm i -g npm@next gulp
install:
  - pip install -r requirements
  - npm install
script:
  - python -m unittest discover tests
  - gulp
  - 'test -z "`git status -s | tee /dev/stderr`" || (echo "Encountered untracked changes after generating e2e test. Did you forget run gulp?" && false)'
  - ./e2e_test.sh
  - ./test_as_dependency.sh

